### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by SebWouters** [sunqm/psi4-cc#1]
Hi Qiming,

I compiled your plugin with the intel compiler and mkl (with commit a6a30638bb19448528ff016f6ff37960560d8402 of psi4public), and get the following error when trying the tests:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import psi4
  File "/home/seba/qimingcc/psi4-cc/test/psi4/__init__.py", line 12, in <module>
    from wrapper import *
  File "/home/seba/qimingcc/psi4-cc/test/psi4/wrapper.py", line 5, in <module>
    import _psi4
ImportError: /opt/intel/composer_xe_2015.0.090/mkl/lib/intel64/libmkl_avx.so: undefined symbol: mkl_dft_compute_forward_d_out_par
```

Any suggestions?

Best,
Seb

**Comment by sunqm** [comment]
Seems the latest MKL library does not work well with gcc compiler.  For icc, the compiler flag -lmkl solves this problem.
